#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py clean
python manage.py build
python manage.py loaddata quiz_app_fixtures.json
python manage.py makemigrations
python manage.py migrate
exec python manage.py runserver 0.0.0.0:8000
