# Generated by Django 3.2.16 on 2023-03-03 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('pmcq', 'Permutation Multiple Choice'), ('pp', "Parson's Problem")], max_length=4)),
                ('correct_answer', models.CharField(max_length=500)),
                ('distractor_1', models.CharField(max_length=500)),
                ('distractor_2', models.CharField(max_length=500)),
                ('distractor_3', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('time_limit', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='quizzes', to='quizzes.QuestionBank')),
            ],
        ),
    ]
