# Generated by Django 3.2.16 on 2023-03-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=1024, verbose_name='stem')),
                ('type', models.IntegerField(choices=[(0, 'MC'), (1, 'PMC'), (2, 'PP')], verbose_name='type')),
                ('explain', models.CharField(max_length=512, verbose_name='explain')),
            ],
            options={
                'verbose_name': 'Question',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G'), (8, 'H')], verbose_name='options')),
                ('content', models.CharField(max_length=256, verbose_name='content')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Option',
                'db_table': 'options',
                'ordering': ['options'],
                'unique_together': {('question', 'content')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G'), (8, 'H')], verbose_name='options')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'db_table': 'answers',
                'ordering': ['options'],
                'unique_together': {('question', 'options')},
            },
        ),
    ]
