# Generated by Django 4.1.6 on 2023-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quiz_gradebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('attempts', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gradebook',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='gradebook',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='gradebook',
            name='student_ids',
        ),
        migrations.DeleteModel(
            name='IntegerModel',
        ),
        migrations.AddField(
            model_name='gradebook',
            name='student_data',
            field=models.ManyToManyField(related_name='student_data', to='quizzes.datamodel'),
        ),
    ]
