# Generated by Django 4.1.6 on 2023-02-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='class_name',
            new_name='course',
        ),
    ]
