# Generated by Django 4.1.6 on 2023-03-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0002_student_user_teacher_user_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakemultiplechoicequestion',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='fakemultiplechoicequestion',
            name='distractors',
        ),
        migrations.AlterField(
            model_name='fakemultiplechoicequestion',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fakemultiplechoicequestion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fakemultiplechoicequestion',
            name='root',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='fakemultiplechoicequestion',
            name='tags',
        ),
        migrations.DeleteModel(
            name='fakeDistractors',
        ),
        migrations.DeleteModel(
            name='fakeSubjectTags',
        ),
        migrations.AddField(
            model_name='fakemultiplechoicequestion',
            name='distractors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fakemultiplechoicequestion',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
