# Generated by Django 4.1.6 on 2023-02-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0002_rename_class_name_quiz_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
    ]
