# Generated by Django 4.1.6 on 2023-02-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0004_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
