# Generated by Django 4.1.6 on 2023-02-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0005_alter_student_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Student ID'),
        ),
    ]
