# Generated by Django 4.1.6 on 2023-02-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0006_remove_student_id_alter_student_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'grades',
            },
        ),
    ]
