# Generated by Django 4.1.6 on 2023-02-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0008_class_gradebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('tid', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Teacher ID')),
                ('classes', models.ManyToManyField(to='quiz_home.class')),
            ],
        ),
    ]
