# Generated by Django 4.1.6 on 2023-02-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0009_multiplechoicequestion_stats_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(to='quiz_home.class'),
        ),
    ]
