# Generated by Django 4.1.6 on 2023-02-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0009_multiplechoicequestion_stats_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructor',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='quizzes',
            field=models.ManyToManyField(to='quiz_home.quiz'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='quiz_home.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ManyToManyField(to='quiz_home.instructor'),
        ),
    ]
