# Generated by Django 4.1.6 on 2023-03-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0010_instructor_class_quizzes_class_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'stats'},
        ),
    ]
