# Generated by Django 4.1.6 on 2023-02-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0010_instructor_class_quizzes_class_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('tid', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Teacher ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'stats'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(to='quiz_home.class'),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='quiz_home.class'),
        ),
    ]
