# Generated by Django 4.1.6 on 2023-03-01 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0012_questionbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('question_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz_home.questionbank')),
                ('subject_tag', models.ManyToManyField(to='quiz_home.subjecttags')),
            ],
        ),
    ]
