# Generated by Django 4.1.6 on 2023-03-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0011_questionbank_alter_stats_options'),
        ('quiz_home', '0014_auto_20230303_2008'),
    ]

    operations = [
    ]
