# Generated by Django 4.1.6 on 2023-03-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0015_merge_20230309_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionBank',
        ),
    ]
