# Generated by Django 4.1.6 on 2023-03-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0016_delete_questionbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='fakeDistractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fakeQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='fakeSubjectTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fakeMultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('hint', models.CharField(blank=True, max_length=100, null=True)),
                ('distractors', models.ManyToManyField(to='quiz_home.fakedistractors')),
                ('tags', models.ManyToManyField(to='quiz_home.fakesubjecttags')),
            ],
        ),
    ]
