# Generated by Django 4.1.6 on 2023-03-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_home', '0017_fakedistractors_fakequestionbank_fakesubjecttags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fakeQuestionBank',
        ),
    ]
